export const remarksMock = [
    {
        id: 1,
        status: "Canceled",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Capital",
        client: "Bruno Lins", 
    },
    {
        id: 2,
        status: "Finished",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Heder", 
    },
    {
        id: 3,
        status: "Canceled",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Capital",
        client: "Kaere", 
    },
    {
        id: 4,
        status: "Finished",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Carlos", 
    },
    {
        id: 5,
        status: "Finished",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Bruno Lins", 
    },
    {
        id: 6,
        status: "Finished",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Bruno Lins", 
    },
    {
        id: 7,
        status: "Canceled",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Bruno Lins", 
    },
    {
        id: 8,
        status: "Canceled",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Bruno Lins", 
    },
    {
        id: 9,
        status: "Finished",
        title: "Apresentação Institucional TCS",
        manager: "Gilberto Anderson",
        topic: "Jornada Digital Itaubers",
        area: "Finanças Risco De Credito Pessoal",
        client: "Bruno Lins", 
    },
]