export const subjectsMock = [
    {
        id: 1,
        status: "Active",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",    

    },
    {
        id: 2,
        status: "Active",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",   
    },
    {
        id: 3,
        status: "Inactive",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 4,
        status: "Active",
       email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 5,
        status: "Active",
        email: "igorsena@tcs.com",
        client: "Guilherme Rezende", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 6,
        status: "Active",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 7,
        status: "Inactive",
       email: "igorsena@tcs.com",
        client: "Guilherme Rezende", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 8,
        status: "Inactive",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
    {
        id: 9,
        status: "Active",
        email: "igorsena@tcs.com",
        client: "Igor Sena", 
        textRole:"Dev Front-End",
        textCostumer:"Itaú",
        textBusiness:"React e Angular",
        textRelease: "Itaú",  
    },
]